# Generated by Django 3.2.12 on 2023-07-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
