# Generated by Django 3.2.12 on 2023-07-19 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_alter_callback_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$')]),
        ),
    ]
