# Generated by Django 3.2.12 on 2023-07-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_alter_callback_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
